### ISSUE TITLE
Hyperlink 'Handling library lists' does not work

### ISSUE THREAD

**Issue by tools400** [WorksOfLiam/barryCI#19]
Hi Liam,

The 'Handling library lists' hyperlink on the main homepage of the wiki does not work. It points to page: https://github.com/WorksOfBarry/barryCI/wiki/Handling-library-lists

Regards,

Thomas.

**Comment by worksofliam** [comment]
Hi @tools400 

Yes, I migrated that page to another document and it can be found here: https://worksofbarry.github.io/rpg-git-book/6-buildtool#handling-library-lists-in-gnu-make

I will fix the wiki now.

Liam
